### ISSUE TITLE
remove license from grammar

### ISSUE THREAD

**Issue by andreoss** [cqfn/eo#410] opened 2021-11-02 23:21 UTC
Let's remove license from grammar and ignore all comments completely 

https://github.com/cqfn/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L44
https://github.com/cqfn/eo/blob/master/eo-parser/src/main/antlr4/org/eolang/parser/Program.g4#L77

**Comment by yegor256** [comment] 2021-11-03 07:48
@andreoss we don't want people to have comments inside objects, only outside and only for abstract ones:

```
# legal comment
[] > hello
  # illegal comment
  42 > x
  # legal comment
  [] > bye
    # illegal one
    stdout > @
      "Hello, world!"
```

**Comment by yegor256** [comment] 2021-11-16 03:48
@andreoss so, it's by design, I'm closing

**Closed by yegor256** 2021-11-16 03:48 UTC
Labels: 0crat/new
