### ISSUE TITLE
first release

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#138] opened 2017-07-09 11:07 UTC
Let's release it to Maven Central. I'll do it now.

**Comment by nlchar** [comment] 2021-01-26 18:50
@yegor256 the issue is surely done, hence I propose closing it.

**Comment by 0crat** [comment] 2021-01-26 18:50
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-802-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#138, Action: `created`

**Comment by 0crat** [comment] 2021-01-26 18:51
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-804-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#138, Action: `created`

**Closed** 2021-02-08 08:34 UTC

**Comment by 0crat** [comment] 2021-02-08 09:09
Job `gh:cqfn/eo#138` is not assigned, can't get performer
