### ISSUE TITLE
let's make it possible to use Java objects inside EO

### ISSUE THREAD

**Issue by yegor256** [cqfn/eo#144] opened 2017-08-06 11:00 UTC
Let's make it possible to use them. Here is how:

```
@java.lang.StringBuilder
  "Hello, world!"
```

This will create an object of class `java.lang.StringBuilder`

**Comment by 0crat** [comment] 2017-08-06 11:00
> @0crat assign me ([here](https://github.com/yegor256/eo/issues/144#issuecomment-320499876))

@yegor256 Job `gh:yegor256/eo#144` assigned to @yegor256, please go ahead ([policy](http://datum.zerocracy.com/pages/policy.html)).

**Comment by 0crat** [comment] 2017-08-06 11:01
+15 points just awarded to @yegor256, total is [+1200](http://www.0crat.com/u/yegor256).

**Comment by 0crat** [comment] 2017-11-14 14:35
@yegor256 this job was assigned to you 8 days ago.
It will be taken away from you after 10 days from start (this is our policy).

**Comment by 0crat** [comment] 2017-11-14 14:36
@yegor256 resigned from `gh:yegor256/eo#144`, please stop working.

**Comment by 0crat** [comment] 2017-11-14 14:36
Oops! Job `gh:yegor256/eo#144` is not assigned to anyone.

**Comment by 0crat** [comment] 2017-11-14 14:37
Oops! Job `gh:yegor256/eo#144` is not assigned to anyone.

**Comment by 0crat** [comment] 2018-04-12 02:35
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment] 2018-04-17 05:36
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by 0crat** [comment] 2018-04-22 07:36
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually or invite more people to the project, as explained in [§51](http://www.zerocracy.com/policy.html#51)

**Comment by yegor256** [comment] 2018-04-23 10:58
@0crat out

**Comment by 0crat** [comment] 2018-04-23 10:58
> @0crat out ([here](https://github.com/yegor256/eo/issues/144#issuecomment-383535935))

@yegor256 GitHub issue is still open, won't close

**Comment by 0crat** [comment] 2018-04-27 08:36
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by 0crat** [comment] 2018-05-02 09:36
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `DEV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment] 2018-05-06 05:08
@0crat out

**Comment by 0crat** [comment] 2018-05-06 05:08
> @0crat out ([here](https://github.com/yegor256/eo/issues/144#issuecomment-386854388))

@yegor256 The job [#144](https://github.com/yegor256/eo/issues/144) is now out of scope

**Comment by nlchar** [comment] 2021-01-26 18:49
@yegor256 I propose closing this issue since it is unmanageable because of its wide objective. We'd better decompose the `Java<--->EO` interoperability bridge later. 
At the moment, the issue is out of the scope of the project. But sooner or later, it will be inside the scope and deep decomposition would be needed.

**Comment by 0crat** [comment] 2021-01-26 18:50
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-802-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#144, Comment: 320499876

**Comment by 0crat** [comment] 2021-01-26 18:50
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-803-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#144, Comment: 383535935

**Comment by 0crat** [comment] 2021-01-26 18:50
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-803-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#144, Action: `created`

**Comment by 0crat** [comment] 2021-01-26 18:51
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@8db67de5-a2dd-48eb-942b-002f7d550524, thread: pool-804-thread-1
com.zerocracy.radars.github.GhProject[69] com.zerocracy.radars.github.GhProjectNotFoundException: Github project for 'cqfn/eo' repo was not found
```

[0.55](https://github.com/zerocracy/farm): Issue: cqfn/eo#144, Comment: 386854388

**Closed** 2021-02-08 08:37 UTC

**Comment by 0crat** [comment] 2021-02-08 09:08
Job `gh:cqfn/eo#144` is not assigned, can't get performer
