### ISSUE TITLE
Why ctor? and why not "constructor"?

### ISSUE THREAD

**Issue by Tertioptus** [cqfn/eo#49] opened 2016-11-30 21:33 UTC
How much does "onstruc" save you?  

It seems like the code is based on an English-language base, why not keep it that way purely?

Developers should be adept with tools like vim, content assist, etc to complete tokens.  This way you don't compromise the clarity of the language for the sake of convenience.

**Comment by alexpanov** [comment] 2016-11-30 22:40
Thank you. I wanted to raise the same issue.
Keywords must be `words` first, keys second

**Comment by aravindps** [comment] 2016-12-01 04:20
I agree!

**Comment by MadridianFox** [comment] 2016-12-01 10:05
👍

**Comment by stain** [comment] 2016-12-01 10:21
Agree, I have never liked "ctor" (C Tor), are there other Tors  as well
then, "dtor" ? (Detour)

If "constructor" is deemed too long (not my view), then perhaps "new" like
in Ruby?

**Comment by mdbs99** [comment] 2016-12-01 12:39
I agree.
When I've started the #29 was about not use "same name of Type for constructors" and not use "~destructor C++ style".

But where were you who didn't vote?
Well, maybe we can change this now.

**Comment by stain** [comment] 2016-12-01 12:58
Sorry, two weeks ago was a busy period for me and I missed #29 - it can be hard to keep track!

Let's have a alternative vote poll instead of changing it back and forward :)

**Comment by alexpanov** [comment] 2016-12-01 16:42
It's just an early draft. Many changes is something that one would only expect at this stage.

**Comment by yegor256** [comment] 2016-12-02 07:24
@Tertioptus for me `constructor` just looks too long, that's why I was in favor of `ctor` in #29. How about `before/after`?

**Comment by moriline** [comment] 2016-12-02 10:31
I think that keyword "new" for constructor is the best way.

**Comment by Lebedevsd** [comment] 2016-12-02 10:39
@moriline why do we need **new** keyword, if instead of it we could directly call **ctor**?

why do you think that `Author.new("a", 1)` is better than `author("a",1)`?

**Comment by moriline** [comment] 2016-12-02 11:54
@Lebedevsd Because "new" keyword(and as a word) means "new object" - this is exactly action what we do with/on type. For example: 

> Author.new("a", 1)

 I order TYPE create NEW object with PARAMS.
"new" - constructor/action which we use on type of Author
```
Author author = Author.new("a", 1){
	String .name
	int .age
	new(String name, int age){
		.name = name
		.age = age
	}
	String name(){
		return .name
	}
	
	int age(){
		return .age
	}
}
```

**Comment by mdbs99** [comment] 2016-12-02 13:05
@moriline I like the idea of using `new` [too] (http://objectpascalprogramming.com/posts/interfaces-eo-metodo-statico-new/), but what happens with` destructor`, which name use if we choose `new` for constructor?

**Comment by mdbs99** [comment] 2016-12-02 13:08
@yegor256 maybe we can use `new` for constructors and `died` for destructors. Both are short.

**Comment by stain** [comment] 2016-12-02 14:00
I think we want to keep the "object forking" like `author("a",1)` -- that might make it easier to support functions as objects or "constructors" that return an object with slightly different types than the original. 

Perhaps when declaring this should be called `call()` or something?  (Python has `__call__()` for this purpose (handle function call), but also `__new__` (make object of this class) and `__init__` (initialize `self` after it has been made). We hopefully won't need as many!

**Comment by mdbs99** [comment] 2016-12-02 14:10
@stain please, no underscore! :)

**Comment by pa9ey** [comment] 2016-12-02 17:28
@yegor256 construct/destroy?

I know that the constructor and destructor are "special" methods in a sense and are called implicitly, but why name them differently than other methods? Methods are normally named as commands or verbs. You wouldn't say `file.reader()`.

**Comment by mdbs99** [comment] 2016-12-02 17:45
@pa9ey maybe create/destroy ?

**Comment by pa9ey** [comment] 2016-12-02 17:48
@mdbs99 Yep. Even better.

**Comment by mdbs99** [comment] 2016-12-02 18:09
@pa9ey I was inspired by Object Pascal (OP).
However, OP has two keywords for constructors and destructors, ie, `constructor` and `destructor`. But they have names too. These names, by convention, are `Create` and `Destroy`.
```
constructor Create(Foo: Integer);
destructor Destroy;
```

**Comment by Tertioptus** [comment] 2016-12-02 18:28
@pa9ey  Yes!  Thus construct and destruct are better than constructor and destructor.  Yet, colloquially, create and destroy are more palatable.  So I'm all in for create and destory. I think David West of Object Thinking would agree.

**Comment by Tertioptus** [comment] 2016-12-02 18:30
Would giving a Type the ability to "create" and "destroy" object of it's specification, would that compromise the existence of objects that have public "create" or "destroy" behaviors.

**Comment by moriline** [comment] 2016-12-02 18:40
@mdbs99 What about this?
```
Book book1 = Book.new("a", "1234"){
	String .title
	String .isbn
	new(String title, String isbn){
		.title = title
		.isbn = isbn
	}
	
	new(String title){
		new(title, "1111")
	}
        die(){
	}
}
```
If we are using destructor maybe ``` die ``` ?

**Comment by NikoGJ** [comment] 2016-12-02 19:04
I agree in favor of making a constructor as a method/message
The same goes for desctructor but why would you want to destruct objects ? (except for technical implementation reasons)?

**Comment by mdbs99** [comment] 2016-12-03 13:06
@moriline I [said](https://github.com/yegor256/eo/issues/49#issuecomment-264450271) `die` too, but I prefer `create` and `destroy` now.

**Comment by mdbs99** [comment] 2016-12-03 13:07
@NikoGJ 
> ...why would you want to destruct objects ? (except for technical implementation reasons)?

If you want that GC — or ref-counting, whatever — release the object *right now*, you call the destructor.

**Comment by Tertioptus** [comment] 2016-12-03 13:57
@mdbs99 

"release" actually makes more sense.   "create" and "release".  But not sure if that is too restrictive.  It seems this language should be interpreter agnostic, such that we could port it to a platform that manages memory.  Maybe I'm getting to far in the weeds.

**Comment by mdbs99** [comment] 2016-12-03 14:36
@Tertioptus it will not be mandatory to call the destructor directly, only if you want.

About "create/release" vs "create/destroy", I choose the last one.
If everybody likes "release", so my vote would be "new/release".

**Comment by stain** [comment] 2016-12-03 16:12
+1 to create/destroy :-)  Also like the Object Pascal reference.

In Java normally the finalise() is protected rather than public (it would
only be called from the GC), but in EO all methods are public.

Would it therefore be possible to call destroy() on an object, even if
other objects still reference it?

Presumably create/destroy are the two only two methods that are allowed to
mutate an EO; but I think destroy() should be idempotent, multiple calls
would be OK. That is, after a first destroy(), field references are freed
(possible calling their destroy through GC or ref count)

After this the object is "dead", every method call will throw an
DestroyedObjectException, except destroy() which would then be a no-op.

On 3 Dec 2016 2:38 pm, "Marcos Douglas B. Santos" <notifications@github.com>
wrote:

@Tertioptus <https://github.com/Tertioptus> it will not be mandatory to
call the destructor directly, only if you want.

About "create/release" vs "create/destroy", I choose the last one.
If everybody likes "release", so my vote would be "new/release".

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/yegor256/eo/issues/49#issuecomment-264642902>, or mute
the thread

**Comment by yegor256** [comment] 2016-12-04 09:29
How about `up`/`down`?

**Comment by yegor256** [comment] 2016-12-04 09:29
How about `+`/`-`?

**Comment by yegor256** [comment] 2016-12-04 09:29
Do we need an open vote here? :)

**Comment by Hronom** [comment] 2016-12-04 10:25
@yegor256 definitely need a vote if you dont creating language only for itself...

Well newest IDE have autocompeltition, so I'm not worried about long names like: `constructor/destructor`, `create/destroy`

**Comment by pa9ey** [comment] 2016-12-04 10:33
@yegor256 How about this? (^; http://poll.lab.io/G5h11XOB__BL8YbksgxErw

**Comment by sergiofigueras** [comment] 2016-12-04 14:31
Guys,

I'm coming just now for that discussion, but lets try to add something.

So, I dont see that a simple board vote will be enough for us, since the problem is not the voting itself, but our arguments to conclude a good approach. Also, I think that is a very special topic where we can't rely on a election for it.

use of CTor and DTor -> ok, it is nice. But as @alexpanov said, we should have keys as last options. It could be an alias for "constructor and destructor", for short. But it is not necessary to be a formal replacement for "Constructor and Destructor".
Constructor and Destructor -> nice too. Its a well established convention and honestly it expresses the correct idea of it.
Before and After -> it have other meanings in other languages and frameworks.
up / down -> doesnt see that it bring us a real value, its quite hard to understand the point of it.
+ / - -> how operators overloading will be treated in EO? Can we do a sum of two different objects? Ex User.new("a") + Group.new("b")? And if I want to overload this "+" operator inside two different classes?

I think that our main concerns on it should be:
1 - use words first, keys only if it is necessary
2 - Usage of words that are not used in different languages with different approaches (like Before and After).

So, I would suggest to use Constructors and Destructors formally and CTors and DTors just as good nicknames and see what happens in the meanwhile. :)

**Comment by pa9ey** [comment] 2016-12-04 14:42
@sergiofigueras I do actually kind of agree. We could do with collecting the best arguments together for each proposed case. But then eventually we would still have to vote. (Unless Yegor vetos it, which I wouldn't particularly mind.)

But all of that is quite a long-winded process. I wouldn't mind having a quick vote for now and then going with something for a bit until we make a proper decision.

**Comment by Tertioptus** [comment] 2016-12-04 19:47
Like myself, I think there are a few non-contributors, so I'm not sure we should have an equal vote.

**I propose that the Republic of EO, vote for their top 3 favorite contributors to the project.**  And those three will vote to make the final decision.  Their work and insight is already on display.

**Comment by yegor256** [comment] 2016-12-05 07:20
My main priority is to make these creatures (ctor and dtor) obviously different from methods. That's why I don't really like `create/destroy` and other English words. That's why `ctor/dtor` is a good option for me, as well as `+/-` (even though semantically they are not really a good fit). See the point?

**Comment by yegor256** [comment] 2016-12-05 07:20
@pa9ey I voted :)

**Comment by Tertioptus** [comment] 2016-12-05 15:39
Okay then, could we just **internationalize** the language itself, such that nominally the keywords are concept-driven.  For all I care, the keywords could all be in abbreviated Latin, as long as my IDE can render it to an American-English set for me.  

_brainstorming babble:
Even the Type level EO docs could contain a has for like translations, just in case someone wrote the code in Russian.

As longs as class names or nouns, and method names are verbs._

**Comment by ixmanuel** [comment] 2017-04-16 16:39
I think "new" operator should be removed from EO, because it is a legacy concept. It comes from languages where we need to deal with their implementation. "new" is about low level operations. "new" does't get along with the different levels of abstraction:

new PersonID means that the machine have to allocate memory, but if an object bring the personID from a data store, then the object is reconstituing the entity but it is not creating a new one (not in the terms of the domain)

If we think that objects are on a stage, they appear as players that interact with each other, but do not need to be born in each scene. They only need to appear on the scenes that are required.

**Comment by ixmanuel** [comment] 2017-05-15 18:54
I think either "constructor" and "new" should be removed from EO, because it is a legacy concept. I don't see the "new" operator in the proposal, but the constructor is there. Therefore, I don't know what was the underlying concept that supports this decision, but I think that it is not consistent: new-constructor came from the same kind of thinking (thinking in terms of how computers work).

If we think that objects are on a stage, they appear as players that interact with each other, but do not need to be born in each scene. They only need to appear on the scenes that are required. 

The actors also require resources, e.g., clothing, tools, that already exist but they don't need to create their clothes each time that they come on the scene. Also, if both players need to collaborate to perform as a giant, they don't born again in order to form the structure.

**Comment by Tertioptus** [comment] 2017-05-15 20:45
Borrowing your scenario, I believe that the constructor is the parameter interface to which the director interacts with, and the method parameters are the interface for the other actors.  Such that during boot strapping of the app, the monolithic global application entity creates all of the objects, composing them via constructors.  Post-creation, the objects interact(communicate) with each other via method parameters.

**Comment by pa9ey** [comment] 2017-05-15 21:51
@ixmanuel I agree that they don't need to be "born" each time. But, if we must use the stage production analogy, there is often a "cast list" at the start of the play. They must at least be described. The "Dramatis personæ", the "actors", are introduced. Are you just arguing about names?

How do you describe what an object is? What it encapsulates? With a special method called `init`?

Is that all you mean?

**Comment by stain** [comment] 2017-05-16 16:27
Well, if  EO objects are truly immutable, and constructors can't do any
work (beyond constructing), then it should be a runtime implementation
detail if they are created once and kept around for subsequent constructor
calls (e.g. memorisation pattern ), always created fresh on demand (like
java's new keyword), or a hybrid of these (soft references in cache).

Perhaps what it comes down to for EO semantics is:

* Does a second, identical constructor call always create a "different"
object? (How can you tell?)
* Can a constructor choose which object it returns, or is "this" always
made/retrieved under the hood?

And perhaps:
* Can a object be uniquely identified using all and only all of its primary
constructor arguments? (e.g. is the constructor functional or can it have
side effects?)

**Comment by stain** [comment] 2017-05-16 16:35
Btw, Python had *two* constructors:


__init__(self, *args, **kwargs) -- similar to in java constructor, "self"
already exists but has no fields set yet.

__new__(cls, *args, **kwargs) -- default implementation in object.__new__
will allocate an empty object of the given class cls as "self" with the
arguments to the __init__ constructor.

Normally people only define a __init__.

Overriding __new__ in Python allows you to "mess around" e.g. rewrite which
(sub)class to instantiate or return a different (e.g. cached) "self".

I don't think EO's philosophy of would be compatible with such "hacking
enablers" - but this could of be an option for how EO constructors are
implemented under the hood on JVM.

**Comment by ixmanuel** [comment] 2017-05-17 14:55
@Tertioptus 
Yes, what we currently name as a constructor, is an interface and the place where initialization occurs, that is, the beginning of an act (beginning could be a good name but is not different from init that is short). With this reasoning we could try other words: **input, interaction, require, use, collaborate**. The parameters come from the mathematical domain and are certainly inputs to the function. In our case, they are also inputs or collaborators. 

@pa9ey 
Yes, it is only about naming. But naming accordingly with the "EO" principles as @stain described: 

>  if  EO objects are truly immutable, and constructors can't do any
work (beyond constructing), then it should be a runtime implementation
detail

**Comment by ixmanuel** [comment] 2017-05-17 15:07
@yegor256 has proposed "ctor" and "dtor", how do you see? "init" and "free".

**Comment by yegor256** [comment] 2021-01-19 02:19
@Tertioptus I'm closing, since EO doesn't have constructors anymore

**Closed by yegor256** 2021-01-19 02:19 UTC
