### ISSUE TITLE
`XMIR::toEO` fails to reproduce the program correctly

### ISSUE THREAD

**Issue by nikololiahim** [cqfn/eo#344] opened 2021-09-21 14:37 UTC
# Problematic Code
```java
System.out.println(
            new XMIR(
                new XMLDocument(
                    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                        "<program ms=\"46\"\n" +
                        "         name=\"mutual_rec\"\n" +
                        "         time=\"2021-09-21T10:36:38.259Z\"\n" +
                        "         version=\"0.5.0\">\n" +
                        "   <listing>+package sandbox\n" +
                        "+alias stdout org.eolang.io.stdout\n" +
                        "+alias sprintf org.eolang.txt.sprintf\n" +
                        "\n" +
                        "[] &gt; base\n" +
                        "  memory &gt; x\n" +
                        "  [self v] &gt; f\n" +
                        "    x.write &gt; @\n" +
                        "      v\n" +
                        "  [self v] &gt; g\n" +
                        "    self.f &gt; @\n" +
                        "      self\n" +
                        "      v\n" +
                        "[] &gt; derived\n" +
                        "  base &gt; @\n" +
                        "  [self v] &gt; f\n" +
                        "    self.g &gt; @\n" +
                        "      self\n" +
                        "      v\n" +
                        "&lt;EOF&gt;</listing>\n" +
                        "   <errors/>\n" +
                        "   <sheets>\n" +
                        "      <sheet>not-empty-atoms</sheet>\n" +
                        "      <sheet>middle-varargs</sheet>\n" +
                        "      <sheet>duplicate-names</sheet>\n" +
                        "      <sheet>many-free-attributes</sheet>\n" +
                        "      <sheet>broken-aliases</sheet>\n" +
                        "      <sheet>duplicate-aliases</sheet>\n" +
                        "      <sheet>one-body</sheet>\n" +
                        "      <sheet>same-line-names</sheet>\n" +
                        "      <sheet>self-naming</sheet>\n" +
                        "      <sheet>add-refs</sheet>\n" +
                        "      <sheet>wrap-method-calls</sheet>\n" +
                        "      <sheet>vars-float-up</sheet>\n" +
                        "      <sheet>add-refs</sheet>\n" +
                        "      <sheet>resolve-aliases</sheet>\n" +
                        "      <sheet>resolve-aliases</sheet>\n" +
                        "      <sheet>add-default-package</sheet>\n" +
                        "      <sheet>broken-refs</sheet>\n" +
                        "      <sheet>unknown-names</sheet>\n" +
                        "      <sheet>noname-attributes</sheet>\n" +
                        "      <sheet>duplicate-names</sheet>\n" +
                        "      <sheet>data-objects</sheet>\n" +
                        "   </sheets>\n" +
                        "   <metas>\n" +
                        "      <meta line=\"1\">\n" +
                        "         <head>package</head>\n" +
                        "         <tail>sandbox</tail>\n" +
                        "         <part>sandbox</part>\n" +
                        "      </meta>\n" +
                        "      <meta line=\"2\">\n" +
                        "         <head>alias</head>\n" +
                        "         <tail>stdout org.eolang.io.stdout</tail>\n" +
                        "         <part>stdout</part>\n" +
                        "         <part>org.eolang.io.stdout</part>\n" +
                        "      </meta>\n" +
                        "      <meta line=\"3\">\n" +
                        "         <head>alias</head>\n" +
                        "         <tail>sprintf org.eolang.txt.sprintf</tail>\n" +
                        "         <part>sprintf</part>\n" +
                        "         <part>org.eolang.txt.sprintf</part>\n" +
                        "      </meta>\n" +
                        "   </metas>\n" +
                        "   <objects>\n" +
                        "      <o line=\"5\" name=\"base\">\n" +
                        "         <o base=\"org.eolang.memory\" line=\"6\" name=\"x\"/>\n" +
                        "         <o line=\"7\" name=\"f\">\n" +
                        "            <o line=\"7\" name=\"self\"/>\n" +
                        "            <o line=\"7\" name=\"v\"/>\n" +
                        "            <o base=\".write\" line=\"8\" method=\"\" name=\"@\">\n" +
                        "               <o base=\"x\" line=\"8\" ref=\"6\"/>\n" +
                        "               <o base=\"v\" line=\"9\" ref=\"7\"/>\n" +
                        "            </o>\n" +
                        "         </o>\n" +
                        "         <o line=\"10\" name=\"g\">\n" +
                        "            <o line=\"10\" name=\"self\"/>\n" +
                        "            <o line=\"10\" name=\"v\"/>\n" +
                        "            <o base=\".f\" line=\"11\" method=\"\" name=\"@\">\n" +
                        "               <o base=\"self\" line=\"11\" ref=\"10\"/>\n" +
                        "               <o base=\"self\" line=\"12\" ref=\"10\"/>\n" +
                        "               <o base=\"v\" line=\"13\" ref=\"10\"/>\n" +
                        "            </o>\n" +
                        "         </o>\n" +
                        "      </o>\n" +
                        "      <o line=\"14\" name=\"derived\">\n" +
                        "         <o base=\"base\" line=\"15\" name=\"@\" ref=\"5\"/>\n" +
                        "         <o line=\"16\" name=\"f\">\n" +
                        "            <o line=\"16\" name=\"self\"/>\n" +
                        "            <o line=\"16\" name=\"v\"/>\n" +
                        "            <o base=\".g\" line=\"17\" method=\"\" name=\"@\">\n" +
                        "               <o base=\"self\" line=\"17\" ref=\"16\"/>\n" +
                        "               <o base=\"self\" line=\"18\" ref=\"16\"/>\n" +
                        "               <o base=\"v\" line=\"19\" ref=\"16\"/>\n" +
                        "            </o>\n" +
                        "         </o>\n" +
                        "      </o>\n" +
                        "   </objects>\n" +
                        "</program>\n"
                )).toEO());
```

# Expected Output:
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[] > base
  memory > x
  [self v] > f
    x.write > @
      v
  [self v] > g
    self.f > @
      self
      v
[] > derived
  base > @
  [self v] > f
    self.g > @
      self
      v

```

# Actual Output:
```
+package sandbox
+alias stdout org.eolang.io.stdout
+alias sprintf org.eolang.txt.sprintf

[f g] > base
  org.eolang.memory > x

[f] > derived
  base > @
```

**Comment by yegor256** [comment] 2021-09-22 06:59
@nikololiahim reproduced and fixed in 319f536

**Comment by yegor256** [comment] 2021-09-22 06:59
@rultor release, tag is `0.5.1`

**Comment by yegor256** [comment] 2021-09-22 07:07
@nikololiahim I believe the problem is fixed. If not, please submit a new ticket.

**Closed by yegor256** 2021-09-22 07:07 UTC
Labels: 0crat/new

**Comment by 0crat** [comment] 2021-09-22 08:50
Job `gh:cqfn/eo#344` is not assigned, can't get performer
